# Generated by Django 3.1 on 2021-04-18 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Apo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='会社名')),
                ('author', models.CharField(max_length=20, verbose_name='代表名')),
                ('apoin', models.DateTimeField(auto_now_add=True, verbose_name='アポ入れた日')),
                ('stuff', models.CharField(max_length=100, verbose_name='詰め直し')),
                ('visit', models.DateTimeField(verbose_name='訪問予定日')),
                ('content', models.TextField(max_length=200, verbose_name='内容')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apo.name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
