# Generated by Django 3.2 on 2021-04-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apo', '0002_auto_20210419_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='jini',
            name='company',
            field=models.CharField(default=1, max_length=50, verbose_name='会社名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jini',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
