# Generated by Django 3.2 on 2021-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apo', '0003_auto_20210421_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='会社名')),
            ],
        ),
        migrations.RemoveField(
            model_name='jini',
            name='company',
        ),
    ]
